#index:
#    path: /
#    controller: App\Controller\DefaultController::index

weather_in_city:
  path: /weather/{country}/{city}
  controller: App\Controller\WeatherController::cityAction
  requirements:
    country: '[a-zA-Z]{2}'
    city: '[a-zA-Z\-]+'

#app_country_index:
#  path: /country
#  controller: App\Controller\CountryController::index
#  methods: GET
#
#app_country_new:
#  path: /country/new
#  controller: App\Controller\CountryController::new
#  methods: GET|POST